### PR TITLE
Add optional loader prop

### PR DESCRIPTION
**Pull request by Exilz**
I feel like this is an important missing feature.
Here you go, I didn't update the demo, though.

### CODE REVIEW

**Comment by msageryd** [comment]
That could be useful, thanks. 

I store thumbnail versions of all of my images and I would like to implement something like this:
https://medium.com/the-react-native-log/progressive-image-loading-in-react-native-ecc88e724343#.vj4xz04b4

Do you know if there is any way to supply a custom render function for the images? Another solution would be to provide an array of thumbnails and let the gallery component do the trick internally. I'll probably look into this in a couple of weeks.

Question:
On line 248 you set loadingView = false if there is no loader. Will RN treat {_false_} the same way as {_null_} when rendering?

**Comment by Exilz** [comment]
@michaelswe I don't like this kind of "medium-like" effect where images are blurred before being displayed. But adding an option to supply a custom render function for images is actually a great idea.

That's what I had in mind before making this PR, but the dependency allowing us to play around with images ([transformable-images](https://github.com/ldn0x7dc/react-native-transformable-image)) made this harder than it looks.

It's totally doable, though but I'm not sure the maintainer of this repo would like this component to become much more complex if it came to handle thumbnails too.

On line 248, RN will not render anything if it encounters `false` 😄  It's the easiest way of writing it I guess.

**Comment by Exilz** [comment]
@ldn0x7dc ping

**Comment by jeffhtli** [comment]
It's great that show progress bar when image is loading, waiting merge this PR. @ldn0x7dc

**Comment by nickw444** [comment]
Also would really benefit from this PR being merged. Is there anything blocking this in particular?

**Comment by Exilz** [comment]
@nickw444 looks like this module isn't maintained anymore, in the meantime, you can still use our maintained version : https://github.com/archriss/react-native-image-gallery

**Pull request closed without merging**
